version: '3'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Node.js Backend
  server:
    build: ./server
    container_name: node_server
    restart: always
    environment:
      DB_HOST: db
      DB_USER: appuser
      DB_PASSWORD: apppassword
      DB_NAME: appdb
      SERVER_PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network


  # React Frontend
  client:
    build: ./client
    container_name: react_client
    restart: always
    environment:
      - REACT_APP_API_URL=http://server:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: