services:
  frontend:
    build:
      context: ./code/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      BACKEND_URL: http://backend:3000  
      ENVIRONMENT: development
      APP_VERSION: 1.0.0
    networks:
      - network

  backend:
    build:
      context: ./code/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      ENVIRONMENT: development
      APP_VERSION: 1.0.0
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: database
      REDIS_NODES: redis
      REDIS_PASSWORD: santosh
      REDIS_TLS: false
    networks:
      - network
    depends_on:
      - db
    

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  db_data:
    driver: local