services:
  frontend:
    build:
      context: ./code/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - BACKEND_URL= http://backend:5000 
    networks:
      - network

networks:
  network:
    driver: bridge